jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --drafts
    ports:
        - 4001:4000
        - 35730:35729
    volumes:
        - /root/src/github.com/dashai/dashai.github.io:/srv/jekyll:Z
